version: '3.8'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    container_name: postgres
      
  redis:
    image: redis
    command: redis-server
    container_name: redis
    
  frontend:
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    build: .\frontend\.
    container_name: frontend
    ports:
      - 5000:5000
      
  backend:
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    build: .\backend\.
    container_name: backend
    ports:
      - 8080:8080