version: '3.8'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    container_name: postgres
    volumes:
      - "C:/Users/Maciek/docker/backfront/database:/var/lib/postgresql/data"
    networks:
      - nginx-network
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - "C:/Users/Maciek/docker/backfront/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - nginx-network
             
  frontend:
    build: .\frontend\.
    container_name: frontend
    ports:
      - 5000:5000
    networks:
      - nginx-network
      
  backend:
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    build: .\backend\.
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - nginx-network
      
  redis:
    image: redis
    command: redis-server
    container_name: redis
    networks:
      - nginx-network
      
volumes:
  database:

networks:
  nginx-network:
    name: nginx-network