version: '3.8'

services:
  frontend:
    environment:
      - ENV REACT_APP_BACKEND_URL=http://localhost:8080
    build: .\frontend\.
    container_name: frontend
    ports:
      - 5000:5000
  backend:
    environment:
      - ENV REQUEST_ORIGIN=http://localhost:5000
    build: .\backend\.
    container_name: backend
    ports:
      - 8080:8080