version: '3.8'

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    build: .
    command: server
    volumes:
      - .\text.log:/usr/src/app/text.log
    container_name: server-web
    ports:
      - 8080:8080